# Python script to extract Context Switch values from files
# generated by the Feather Trace tools 

# Generates Plot for all 8 cores overlapped

import math
import matplotlib.pyplot as plt

fPrefix = raw_input("* Enter File Name: ")
respA = []

for i in range(0, 8):
	fName = fPrefix + str(i)
	fp = open( fName, 'r')
	for line in fp:
		data = line.split()
		resp = data[2]
		resp = int(resp)
		respA.append(resp)

	plt.plot(respA)
	respA = []

# Show the overlapped plot generated
plt.ylabel('Context Switch Overhead')
plt.xlabel('Cycles')
# Rename the title depending upon the scheduler being traced
plt.title('PSN-EDF on 8 Cores')
plt.show()
