# Python script to extract Context Switch values from files
# generated by the Feather Trace tools 

# Generates Plot for each core separately

import math
import matplotlib.pyplot as plt

# Enter the file name of the trace file generated by Feather Trace tools
fName = raw_input("* Enter File Name: ")
fp = open( fName, 'r')
respA = []

for line in fp:
	data = line.split()
	resp = data[2]
	resp = int(resp)
	respA.append(resp)

# Show the plot generated
plt.plot(respA)
plt.ylabel('Context Switch Overhead')
plt.xlabel('Cycles')
plt.title(fName[2:])
plt.show()
