# Python script to extract Context Switch and Scheduling latency values from trace files
# generated by Lttng linux trace tool

import math
import matplotlib.pyplot as plt

# Should run this script in the following format
# python LinuxTrace.py 

# Enter the file name of the trace file generated by Lttng
fName = raw_input("* Enter File Name: ")
fp = open( fName, 'r')
# Enter the CPU Id to be extracted 
# Example CPU Id 1 will extract the trace of the application from cpu core 1
cpu = raw_input("* Enter CPU Id: ")
cpu = int(cpu)
over = []
for line in fp:
	tokens = line.split(" ")
	token = tokens[12].split(",")
	if('"track"' == token[0]):
		if(cpu == int(tokens[7])):
			lat = tokens[1].split("+")[1][:-1]
			lat = float(lat)
			lat = lat * (1000000000)
			lat = int(lat)
			over.append(lat)

# Show the plot generated
plt.plot(over)
# Replace the 'Scheduling Latency' with 'Context Switch Overhead' when tracing for Context switch overhead
plt.ylabel('Context Switch Overhead')
plt.xlabel('Cycles')
string = "Linux" + str(cpu)
plt.title(string)
plt.show()
