# Python script to extract Context Switch and Scheduling latency values from trace files
# generated by Lttng linux trace tool

import math
import matplotlib.pyplot as plt

# Should run this script in the following format
# python LinuxTrace.py 

fName = "ContextSwitchTrace" 
#fName = "SchedulingLatency" 
for cpu in range(0, 8):
	# Enter the file name of the trace file generated by Lttng
	fp = open( fName, 'r')
	# Enter the CPU Id to be extracted 
	# Example CPU Id 1 will extract the trace of the application from cpu core 1
	over = []
	for line in fp:
		tokens = line.split(" ")
		token = tokens[12].split(",")
		if('"track"' == token[0]):
			if(cpu == int(tokens[7])):
				lat = tokens[1].split("+")[1][:-1]
				lat = float(lat)
				lat = lat * (1000000000)
				lat = int(lat)
				over.append(lat)

	plt.plot(over)
# Replace the 'Scheduling Latency' with 'Context Switch Overhead' when tracing for Context switch overhead
plt.ylabel('Context Switch Overhead')
#plt.ylabel('Scheduling Latency')
plt.xlabel('Cycles')
plt.title('Linux CFS on 8 Cores')
# Show the plot generated
plt.show()
