# Python script to extract Respose time values from files
# generated by the Target Tracking application

# Should run this script in the following format
# python LinuxResp.py >> ReponseTimes13

# The above command considers thirteen tasks 
# The ResponseTimes13 file consists of Max, Min and Avg response times of each task 

import math
import matplotlib.pyplot as plt

out = []

# fNum -> Number of Tasks which have been run. Ex: Here 13 Tasks were run
fNum = 13

# Loop through each file generated by each Task to get each job's response time
for i in range(1, fNum+1):
	fName = "Resp" + str(i)
	fp = open( fName, 'r')
	respA = []
	maxR = 0
	minR = 10000000000
	for line in fp:
		tokens = line.split(",")
		resp = int(tokens[1][:-1])
		if(0 > resp):
			resp += 1000000000

		if(resp > maxR):
			maxR = resp
		if(resp < minR):
			minR = resp
		respA.append(resp)

	# Overlap each Tasks response time graph
	plt.plot(respA)
	plt.ylabel('Response Time')
	plt.xlabel('Jobs')
	
	# Print the Max, Min and Avg response times 
	print "* Task" + str(i)
	print "\tMax Response Time: ", maxR
	print "\tMin Response Time: ", minR
	print "\tAvg Response Time: ", (maxR + minR)/2

# Show the plot generated
plt.title(str(i) + " Tasks")
plt.show()
