# Python script to extract Respose time values from files
# generated by the Feather Trace and sched_trace tools 

# Should run this script in the following format
# python respTime.py >> ReponseTimes13

# The above command considers thirteen tasks 
# The ResponseTimes13 file consists of Max, Min and Avg response times of each task 

import math
import matplotlib.pyplot as plt

# Replace fName for each overload. Here assumed for 30 Tasks
fName = "RespPFAIR15"
fp = open( fName, 'r')
task = -1
jobs = 0
tmiss = 0
tardi = 0 
maxR = 0
minR = 10000000000
maxRA = []
minRA = []
respA = []
string = ""
for line in fp:
	if('#' == line[0]):
		task+=1
		jobs = 0
		if(task > 1):
			maxRA.append(maxR)
			minRA.append(minR)
			plt.plot(respA)
			respA = []
		maxR = 0
		minR = 10000000000
		continue

	data = line.split()
	jobs += 1
	miss = data[4]
	miss = miss[:-1]
	if(1 == int(miss)):
		miss = data[6]
		miss = miss[:-1]
		tardi = int(miss) 
		tmiss+=1
		print "* Task %d Job %d -> Deadline Miss: Tardiness %d" % (task, jobs, tardi)

	resp = data[3]
	resp = resp[:-1]
	resp = int(resp)
	if(resp > maxR):
		maxR = resp
	if(resp < minR):
		minR = resp

	respA.append(resp)

maxRA.append(maxR)
minRA.append(minR)
plt.plot(respA)
plt.ylabel('Response Time')
plt.xlabel('Jobs')
plt.title(fName[4:9] + " " + str(task) + " Tasks")
plt.show()
print "-" * 20
print "* Total Tasks: ", task
print "* Total Jobs per Task: ", jobs
print "* Total Deadline misses: ", tmiss
print "* Max Response Times: ", maxRA
print "* Min Response Times: ", minRA
print "-" * 20
